spring.application.name=chess
spring.datasource.url=jdbc:sqlserver://BB;instanceName=SQL2025;databaseName=ChessDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

server.error.whitelabel.enabled = false
server.error.path=/error

spring.profiles.active=prod
