spring.application.name=sah
spring.datasource.url=jdbc:sqlserver://DESKTOP-KS4BPR9:1433;databaseName=ChessDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=chess
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


spring.profiles.active=prod
